language: bash
services: docker

env:
  matrix:
  - SOLR_VER=8.5.0 TAGS="${SOLR_VER},8.5,8,latest"
  - SOLR_VER=8.4.1 TAGS="${SOLR_VER},8.4"
  - SOLR_VER=8.3.1 TAGS="${SOLR_VER},8.3"
  - SOLR_VER=8.2.0 TAGS="${SOLR_VER},8.2"
  - SOLR_VER=8.1.1 TAGS="${SOLR_VER},8.1"
  - SOLR_VER=8.0.0 TAGS="${SOLR_VER},8.0"
  - SOLR_VER=7.7.2 TAGS="${SOLR_VER},7.7,7"
  - SOLR_VER=7.6.0 TAGS="${SOLR_VER},7.6"
  - SOLR_VER=7.5.0 TAGS="${SOLR_VER},7.5"
  - SOLR_VER=6.6.6 TAGS="${SOLR_VER},6.6,6"
  - SOLR_VER=5.5.5 TAGS="${SOLR_VER},5.5,5"

script:
- cd "${SOLR_VER:0:3}/alpine"
- travis_retry make

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
